/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arthur.scoretarot;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arthu
 */
public class ScoreTarot extends javax.swing.JFrame {

    /**
     * Creates new form ScoreTarot
     */
    public ScoreTarot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ccbox_bouts = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        butt_petite = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_score = new javax.swing.JLabel();
        butt_garde = new javax.swing.JRadioButton();
        butt_poignee = new javax.swing.JRadioButton();
        txt_points = new javax.swing.JTextField();
        butt_petit = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        butt_ajouter = new javax.swing.JButton();
        butt_score = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtab_players = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        butt_add = new javax.swing.JButton();
        txt_preneur = new javax.swing.JTextField();
        txt_appele = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        butt_test = new javax.swing.JButton();
        lbl_num_partie = new javax.swing.JLabel();
        lbl_nb_parties = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ccbox_bouts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));

        jLabel2.setText("Bouts");

        butt_petite.setText("petite");

        jLabel1.setText("Bonus:");

        lbl_score.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        butt_garde.setText("garde");
        butt_garde.setIconTextGap(8);

        butt_poignee.setText("Poignée");
        butt_poignee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_poigneeActionPerformed(evt);
            }
        });

        butt_petit.setText("Petit au bout");
        butt_petit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_petitActionPerformed(evt);
            }
        });

        jLabel3.setText("Points:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Total:");

        butt_ajouter.setLabel("Ajouter");
        butt_ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_ajouterMouseClicked(evt);
            }
        });

        butt_score.setText("Calcul Score");
        butt_score.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_scoreMouseClicked(evt);
            }
        });
        butt_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_scoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(butt_petite))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ccbox_bouts, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_points, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(butt_score)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(butt_garde)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_score, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butt_poignee)
                    .addComponent(butt_petit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butt_ajouter)
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butt_petite, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butt_garde, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccbox_bouts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_points, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(butt_petit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butt_poignee)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lbl_score, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(butt_score)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butt_ajouter)
                .addContainerGap())
        );

        jtab_players.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Joueurs", "", "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtab_players.setRowHeight(25);
        jtab_players.getColumnModel().getColumn(0).setPreferredWidth(100);
        jScrollPane1.setViewportView(jtab_players);

        jButton1.setText("Delete Player");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Add Player");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        butt_add.setText("Nouvelle partie");
        butt_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_addMouseClicked(evt);
            }
        });
        butt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_addActionPerformed(evt);
            }
        });

        txt_preneur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_preneurActionPerformed(evt);
            }
        });

        jLabel6.setText("Preneur");

        jLabel7.setText("(Joueur appelé)");

        butt_test.setText("TEST");
        butt_test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_testMouseClicked(evt);
            }
        });

        lbl_num_partie.setText("0");

        lbl_nb_parties.setText("0");

        jLabel5.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_num_partie, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_preneur, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_appele, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(butt_add))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(butt_test)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_nb_parties, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_preneur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_appele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(lbl_num_partie, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(lbl_nb_parties, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(butt_test)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butt_add)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butt_poigneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_poigneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_poigneeActionPerformed

    private void butt_petitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_petitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_petitActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String player = JOptionPane.showInputDialog(null,"Entrez le nom du joueur: " ,"Add", JOptionPane.INFORMATION_MESSAGE);
        DefaultTableModel modele = (DefaultTableModel) jtab_players.getModel();
        int j=0;
        for(int i=0;i<jtab_players.getRowCount();i++){
            if(jtab_players.getValueAt(i, 0).equals("")){
                j++;
            }
        }
        if(j==0){
            JOptionPane.showMessageDialog(null,"5 joueurs max !" ,"Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            j = 5-j;
            jtab_players.setValueAt(player, j, 0);
        }
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void butt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_addActionPerformed
        DefaultTableModel modele = (DefaultTableModel) jtab_players.getModel();
        for(int i=0;i<=modele.getRowCount()-1;i++){
            for(int j=0;j<=modele.getColumnCount()-1;j++){
                modele.setValueAt("", i, j);
            }
        }
        lbl_num_partie.setText("1");
        
        String[] parties = {"3", "5", "10"};
        JOptionPane jop = new JOptionPane();
        int choix = jop.showOptionDialog(null, "Combien de parties souhaitez-vous jouer ?","Nombre de parties",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE,null,parties,parties[0]);
        int nb_parties;
        if("3".equals(parties[choix])){
            nb_parties = 3;
        }
        else{
            if("5".equals(parties[choix])){
                nb_parties = 5;
            }
            else{
                nb_parties = 10;
            }
        }
        lbl_nb_parties.setText(parties[choix]);
        for(int i=1;i<=nb_parties;i++){
            String j = String.valueOf(i);
            jtab_players.getColumnModel().getColumn(i).setHeaderValue(j);
        }
        jtab_players.getColumnModel().getColumn(nb_parties+1).setHeaderValue("Total");
    }//GEN-LAST:event_butt_addActionPerformed

    private void butt_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_addMouseClicked
        

    }//GEN-LAST:event_butt_addMouseClicked
  
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultTableModel modele = (DefaultTableModel) jtab_players.getModel();
        if(jtab_players.getSelectedRow() == -1){
            JOptionPane.showInternalMessageDialog(null,"Il n'y a pas de ligne séléctionée ! " ,"Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            int ligne = jtab_players.getSelectedRow();
            modele.setValueAt("",ligne,0);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void txt_preneurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_preneurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_preneurActionPerformed

    private void butt_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_scoreActionPerformed

    private void butt_scoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_scoreMouseClicked
        int score;
        int objectif = 0;
        String v_bouts = (String) ccbox_bouts.getSelectedItem();
        int bouts =Integer.parseInt(v_bouts);
        String v_points = txt_points.getText();
        int points = Integer.parseInt(v_points);
        
        switch(bouts){
            case 0:
                objectif = 61;
                break;
            case 1:
                objectif = 51;
                break;
            case 2:
                objectif = 41;
                break;
            case 3:
                objectif = 31;
                break;
        }
        score = points - objectif;
        System.out.println(objectif);
        
        if(butt_petite.isSelected() == true){
            if(score < 0){
                score = score - 25;
            }else{
                score = score + 25;
                if(butt_poignee.isSelected() == true){
                    score = score + 20;
                }
                if(butt_petit.isSelected() == true){
                    score = score + 10;
                }
            }
        }
        if(butt_garde.isSelected() == true){
            if(score < 0){
                score = (score - 25)*2;
            }else{
                score = (score + 25)*2;
                if(butt_poignee.isSelected() == true){
                    score = score + 20;
                }
                if(butt_petit.isSelected() == true){
                    score = score + 10;
                }
            }
        }
        
        String s = Integer.toString(score);
        lbl_score.setText(s);
        
    }//GEN-LAST:event_butt_scoreMouseClicked

    private void butt_ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_ajouterMouseClicked
        DefaultTableModel modele = (DefaultTableModel) jtab_players.getModel();
        int num_partie=1;
        while(!modele.getValueAt(0, num_partie).equals("")){
            num_partie++;
        }
        int nb_joueurs = 0;
        for(int i=0;i<modele.getRowCount();i++){
            if(modele.getValueAt(i,0) != null){    
                nb_joueurs++;
            }
        }
        
        String v_resultat = lbl_score.getText();
        int resultat = Integer.parseInt(v_resultat);
        int autres;
        int score_preneur;
        int score_preneur2;
        String preneur = txt_preneur.getText();
        int num_preneur = -1;
        String appele = txt_appele.getText();
        int num_appele = -1;
        String autre;
        String autre2;
        String autre3;
        String autre4;
        
        for(int i=0;i<=nb_joueurs-1;i++){
            if(((String) modele.getValueAt(i, 0)).equals(preneur)){
                num_preneur = i;
            }
            if(((String) modele.getValueAt(i, 0)).equals(appele)){
                num_appele = i;
            }
        }
        
        switch(nb_joueurs){
            case 3:
                score_preneur = resultat * 2;
                autres = -resultat;
                modele.setValueAt(score_preneur, num_preneur, num_partie);
                for(int j= 0;j< nb_joueurs;j++){
                    if(j != num_preneur){
                        modele.setValueAt(autres, j, num_partie);
                    }
            
                }
                break;
            case 4:
                score_preneur = resultat * 3;
                autres = -resultat;
                modele.setValueAt(score_preneur, num_preneur, num_partie);
                for(int j= 0;j< nb_joueurs;j++){
                    if(j!= num_preneur){
                        modele.setValueAt(autres, j, num_partie);
                    }
               
                }
                break;
            case 5:
                if(num_appele==-1){
                    JOptionPane.showMessageDialog(null,"Vous n'avez pas saisie l'appelé ! " ,"Warning", JOptionPane.INFORMATION_MESSAGE);
                }
                if(num_preneur==-1){
                    JOptionPane.showMessageDialog(null,"Vous n'avez pas saisie le preneur ! " ,"Warning", JOptionPane.INFORMATION_MESSAGE);
                }
                score_preneur = resultat * 4;
                score_preneur2 = resultat;
                autres = -resultat;
                
                modele.setValueAt(score_preneur, num_preneur, num_partie);
                modele.setValueAt(score_preneur, num_appele, num_partie);
                for(int j= 0;j< nb_joueurs;j++){
                    if(j != num_preneur && j != num_appele){
                        modele.setValueAt(autres, j, num_partie);
                    }
                }
                break;
        }
        lbl_num_partie.setText(String.valueOf(num_partie));
        if(lbl_num_partie.getText().equals(lbl_nb_parties.getText())){
            int max=0;
            String gagnant = null;
            for(int i=0;i<nb_joueurs;i++){
                int total=0;
                for(int j=1;j<num_partie;j++){
                    int valeur =(Integer) modele.getValueAt(i, j);
                    total=total+valeur;
                }
                modele.setValueAt(total, i, num_partie+1);
                if(total > max){
                    max = total;
                    gagnant = (String) jtab_players.getValueAt(i,0);
                }
            }
            JOptionPane.showMessageDialog(null,"Fin de la partie! Le gagnant est: " + gagnant,"Fin de la partie", JOptionPane.INFORMATION_MESSAGE);
            
        }
        lbl_score.setText("");
        txt_appele.setText("");
        txt_points.setText("");
        txt_preneur.setText("");
        ccbox_bouts.setSelectedIndex(0);
        butt_garde.setSelected(false);
        butt_petite.setSelected(false);
        butt_petit.setSelected(false);
        butt_poignee.setSelected(false);
    }//GEN-LAST:event_butt_ajouterMouseClicked

    private void butt_testMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_testMouseClicked
        for(int i=0;i<jtab_players.getColumnCount();i++){
            System.out.println("Colonne numéro: "+ i);
        }
        for(int j=0;j<jtab_players.getRowCount();j++){
            System.out.println("Ligne numéro: "+ j);
        }
        System.out.println(jtab_players.getValueAt(1, 1));
    }//GEN-LAST:event_butt_testMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreTarot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreTarot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreTarot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreTarot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreTarot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butt_add;
    private javax.swing.JButton butt_ajouter;
    private javax.swing.JRadioButton butt_garde;
    private javax.swing.JRadioButton butt_petit;
    private javax.swing.JRadioButton butt_petite;
    private javax.swing.JRadioButton butt_poignee;
    private javax.swing.JButton butt_score;
    private javax.swing.JButton butt_test;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> ccbox_bouts;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtab_players;
    private javax.swing.JLabel lbl_nb_parties;
    private javax.swing.JLabel lbl_num_partie;
    private javax.swing.JLabel lbl_score;
    private javax.swing.JTextField txt_appele;
    private javax.swing.JTextField txt_points;
    private javax.swing.JTextField txt_preneur;
    // End of variables declaration//GEN-END:variables
}
